apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component }}
  labels:
    app: {{ .Values.component }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.component }}
  template:
    metadata:
      labels:
        app: {{ .Values.component }}
    spec:
      serviceAccountName: catalogue-sa
      volumes:
        - name: parameters-storage
          emptyDir: {}
      containers:
        - name: {{ .Values.component }}
          image: 058264090525.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.component }}:{{ .Values.image_tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.container_port }}
          volumeMounts:
            - name: parameters-storage
              mountPath: /parameters-storage
      initContainers:
        - name: "{{ .Values.component }}-parameters-container"
          image: 058264090525.dkr.ecr.us-east-1.amazonaws.com/aws-ps-init-cont:12
          imagePullPolicy: Always
          env:
            - name: PARAMETERS
              value: {{ .Values.PARAMETERS }}
          volumeMounts:
            - name: parameters-storage
              mountPath: /parameters-storage