apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: {{ .Values.component }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.component }}
  template:
    metadata:
      labels:
        app: {{ .Values.component }}
    spec:
      containers:
        - name: {{ .Values.component }}
          image: 058264090525.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.component }}:{{ .Values.image_tag }}
          ports:
            - containerPort: 80