apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.component | trimSuffix "-stage" }}"
spec:
  type: {{ .Values.service_type }}
  selector:
    app: {{ .Values.component }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.target_port }}
